spring:
  application:
    name: third-party
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.239.124:8848
server:
  port: 30000

oss:
  accessId: LTAI5tBbGXDAYRJwFGotccXh
  accessKey: Wlw0EWtC2stqIuV3LRbH75kdEgkEax
  endpoint: oss-cn-beijing.aliyuncs.com
  bucket: felcon-mall

