spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall_sms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    hikari:
      pool-name: HikariThreadPool
      minimum-idle: 5
      idle-timeout: 1800000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: 101.42.239.124:8848
#        namespace: gulimail-coupon
#classpath只扫描自己的类路径下的，classpath* 自己的和引入的jar包里面的
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto #全局唯一ID


### 自定义配置
#mq:
#  defaultExchange: amqpExchange # 默认交换器
#  queue: queue # 队列名
#  routeKey: queue_key # 路由key

